### ISSUE TITLE
pubsublite BacklogLocation

### ISSUE THREAD

**Issue by eaball35** [GoogleCloudPlatform/java-docs-samples#5701]
Can't compile tests when updating dependency com.google.cloud:pubsublite-beam-io to v0.17.0 due to BacklogLocation file location [update](https://github.com/googleapis/java-pubsublite/commit/70749d8f4c9cc23937fbb332a5fd168be4ac0d2f). #5699

```
#
# pubsublite/streaming-analytics
#

[ERROR] COMPILATION ERROR :
[ERROR] /tmpfs/src/github/java-docs-samples/pubsublite/streaming-analytics/src/test/java/PubsubliteToGcsIT.java:[29,47] cannot find symbol
  symbol:   class BacklogLocation
  location: interface com.google.cloud.pubsublite.AdminClient
[ERROR] /tmpfs/src/github/java-docs-samples/pubsublite/streaming-analytics/src/test/java/PubsubliteToGcsIT.java:[117,56] cannot find symbol
  symbol:   variable BacklogLocation
  location: class PubsubliteToGcsIT
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project pubsublite-streaming: Compilation failure: Compilation failure:
[ERROR] /tmpfs/src/github/java-docs-samples/pubsublite/streaming-analytics/src/test/java/PubsubliteToGcsIT.java:[29,47] cannot find symbol
[ERROR]   symbol:   class BacklogLocation
[ERROR]   location: interface com.google.cloud.pubsublite.AdminClient
[ERROR] /tmpfs/src/github/java-docs-samples/pubsublite/streaming-analytics/src/test/java/PubsubliteToGcsIT.java:[117,56] cannot find symbol
[ERROR]   symbol:   variable BacklogLocation
[ERROR]   location: class PubsubliteToGcsIT
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

 Testing failed: Maven returned a non-zero exit code.



err: exit status 1
```

**Comment by eaball35** [comment]
Fixed with #5699
