### PR TITLE
deps: added temp fix for auth

### LINKED ISSUE #3540: Monitoring breaks w/ Libraries-BOM 9.0.0
Found in #3534 
```
------------------------------------------------------------
- testing monitoring/cloud-client
------------------------------------------------------------
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.509 s <<< FAILURE! - in com.example.monitoring.QuickstartSampleIT
[ERROR] com.example.monitoring.QuickstartSampleIT.testQuickstart  Time elapsed: 0.314 s  <<< ERROR!
java.lang.NoClassDefFoundError: com/google/auth/oauth2/ServiceAccountJwtAccessCredentials
	at com.example.monitoring.QuickstartSampleIT.testQuickstart(QuickstartSampleIT.java:63)
Caused by: java.lang.ClassNotFoundException: com.google.auth.oauth2.ServiceAccountJwtAccessCredentials
	at com.example.monitoring.QuickstartSampleIT.testQuickstart(QuickstartSampleIT.java:63)

[ERROR] Tests run: 8, Failures: 0, Errors: 8, Skipped: 0, Time elapsed: 0.119 s <<< FAILURE! - in com.example.monitoring.SnippetsIT
[ERROR] com.example.monitoring.SnippetsIT.testGetMetricsDescriptor  Time elapsed: 0.075 s  <<< ERROR!
java.lang.NoClassDefFoundError: com/google/auth/oauth2/ServiceAccountJwtAccessCredentials
	at com.example.monitoring.SnippetsIT.testGetMetricsDescriptor(SnippetsIT.java:77)
Caused by: java.lang.ClassNotFoundException: com.google.auth.oauth2.ServiceAccountJwtAccessCredentials
	at com.example.monitoring.SnippetsIT.testGetMetricsDescriptor(SnippetsIT.java:77)

[ERROR] com.example.monitoring.SnippetsIT.testListTimeSeriesHeader  Time elapsed: 0.004 s  <<< ERROR!
java.lang.NoClassDefFoundError: com/google/auth/oauth2/ServiceAccountJwtAccessCredentials
	at com.example.monitoring.SnippetsIT.testListTimeSeriesHeader(SnippetsIT.java:103)
Caused by: java.lang.ClassNotFoundException: com.google.auth.oauth2.ServiceAccountJwtAccessCredentials
	at com.example.monitoring.SnippetsIT.testListTimeSeriesHeader(SnippetsIT.java:103)

[ERROR] com.example.monitoring.SnippetsIT.testListResources  Time elapsed: 0.003 s  <<< ERROR!
java.lang.NoClassDefFoundError: com/google/auth/oauth2/ServiceAccountJwtAccessCredentials
	at com.example.monitoring.SnippetsIT.testListResources(SnippetsIT.java:155)
Caused by: java.lang.ClassNotFoundException: com.google.auth.oauth2.ServiceAccountJwtAccessCredentials
	at com.example.monitoring.SnippetsIT.testListResources(SnippetsIT.java:155)

[ERROR] com.example.monitoring.SnippetsIT.testListTimeSeriesReduce  Time elapsed: 0.003 s  <<< ERROR!
java.lang.NoClassDefFoundError: com/google/auth/oauth2/ServiceAccountJwtAccessCredentials
	at com.example.monitoring.SnippetsIT.testListTimeSeriesReduce(SnippetsIT.java:129)
Caused by: java.lang.ClassNotFoundException: com.google.auth.oauth2.ServiceAccountJwtAccessCredentials
	at com.example.monitoring.SnippetsIT.testListTimeSeriesReduce(SnippetsIT.java:129)

[ERROR] com.example.monitoring.SnippetsIT.testListTimeSeriesAggregate  Time elapsed: 0.003 s  <<< ERROR!
java.lang.NoClassDefFoundError: com/google/auth/oauth2/ServiceAccountJwtAccessCredentials
	at com.example.monitoring.SnippetsIT.testListTimeSeriesAggregate(SnippetsIT.java:116)
Caused by: java.lang.ClassNotFoundException: com.google.auth.oauth2.ServiceAccountJwtAccessCredentials
	at com.example.monitoring.SnippetsIT.testListTimeSeriesAggregate(SnippetsIT.java:116)

[ERROR] com.example.monitoring.SnippetsIT.testGetResource  Time elapsed: 0.003 s  <<< ERROR!
java.lang.NoClassDefFoundError: com/google/auth/oauth2/ServiceAccountJwtAccessCredentials
	at com.example.monitoring.SnippetsIT.testGetResource(SnippetsIT.java:142)
Caused by: java.lang.ClassNotFoundException: com.google.auth.oauth2.ServiceAccountJwtAccessCredentials
	at com.example.monitoring.SnippetsIT.testGetResource(SnippetsIT.java:142)

[ERROR] com.example.monitoring.SnippetsIT.testListMetricsDescriptor  Time elapsed: 0.003 s  <<< ERROR!
java.lang.NoClassDefFoundError: com/google/auth/oauth2/ServiceAccountJwtAccessCredentials
	at com.example.monitoring.SnippetsIT.testListMetricsDescriptor(SnippetsIT.java:65)
Caused by: java.lang.ClassNotFoundException: com.google.auth.oauth2.ServiceAccountJwtAccessCredentials
	at com.example.monitoring.SnippetsIT.testListMetricsDescriptor(SnippetsIT.java:65)

[ERROR] com.example.monitoring.SnippetsIT.testListTimeSeries  Time elapsed: 0.003 s  <<< ERROR!
java.lang.NoClassDefFoundError: com/google/auth/oauth2/ServiceAccountJwtAccessCredentials
	at com.example.monitoring.SnippetsIT.testListTimeSeries(SnippetsIT.java:90)
Caused by: java.lang.ClassNotFoundException: com.google.auth.oauth2.ServiceAccountJwtAccessCredentials
	at com.example.monitoring.SnippetsIT.testListTimeSeries(SnippetsIT.java:90)

[ERROR] Errors:
[ERROR]   QuickstartSampleIT.testQuickstart:63 » NoClassDefFound com/google/auth/oauth2/...
[ERROR]   SnippetsIT.testGetMetricsDescriptor:77 » NoClassDefFound com/google/auth/oauth...
[ERROR]   SnippetsIT.testGetResource:142 » NoClassDefFound com/google/auth/oauth2/Servic...
[ERROR]   SnippetsIT.testListMetricsDescriptor:65 » NoClassDefFound com/google/auth/oaut...
[ERROR]   SnippetsIT.testListResources:155 » NoClassDefFound com/google/auth/oauth2/Serv...
[ERROR]   SnippetsIT.testListTimeSeries:90 » NoClassDefFound com/google/auth/oauth2/Serv...
[ERROR]   SnippetsIT.testListTimeSeriesAggregate:116 » NoClassDefFound com/google/auth/o...
[ERROR]   SnippetsIT.testListTimeSeriesHeader:103 » NoClassDefFound com/google/auth/oaut...
[ERROR]   SnippetsIT.testListTimeSeriesReduce:129 » NoClassDefFound com/google/auth/oaut...
[ERROR] Tests run: 9, Failures: 0, Errors: 9, Skipped: 0
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.0.0-M4:verify (default) on project monitoring-google-cloud-samples: There are test failures.

------------------------------------------------------------
- testing monitoring/v3
------------------------------------------------------------
[ERROR] Tests run: 6, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 0.732 s <<< FAILURE! - in com.example.UptimeIT
[ERROR] com.example.UptimeIT.test1_CreateUptimeCheck  Time elapsed: 0.484 s  <<< ERROR!
java.lang.NoClassDefFoundError: com/google/auth/oauth2/ServiceAccountJwtAccessCredentials
	at com.example.UptimeIT.test1_CreateUptimeCheck(UptimeIT.java:62)
Caused by: java.lang.ClassNotFoundException: com.google.auth.oauth2.ServiceAccountJwtAccessCredentials
	at com.example.UptimeIT.test1_CreateUptimeCheck(UptimeIT.java:62)

[ERROR] com.example.UptimeIT.test2_GetUptimeCheck  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: com/google/auth/oauth2/ServiceAccountJwtAccessCredentials
	at com.example.UptimeIT.test2_GetUptimeCheck(UptimeIT.java:74)
Caused by: java.lang.ClassNotFoundException: com.google.auth.oauth2.ServiceAccountJwtAccessCredentials
	at com.example.UptimeIT.test2_GetUptimeCheck(UptimeIT.java:74)

[ERROR] com.example.UptimeIT.test2_ListUptimeChecks  Time elapsed: 0.006 s  <<< ERROR!
java.lang.NoClassDefFoundError: com/google/auth/oauth2/ServiceAccountJwtAccessCredentials
	at com.example.UptimeIT.test2_ListUptimeChecks(UptimeIT.java:80)
Caused by: java.lang.ClassNotFoundException: com.google.auth.oauth2.ServiceAccountJwtAccessCredentials
	at com.example.UptimeIT.test2_ListUptimeChecks(UptimeIT.java:80)

[ERROR] com.example.UptimeIT.test2_ListUptimeIps  Time elapsed: 0.003 s  <<< ERROR!
java.lang.NoClassDefFoundError: com/google/auth/oauth2/ServiceAccountJwtAccessCredentials
	at com.example.UptimeIT.test2_ListUptimeIps(UptimeIT.java:87)
Caused by: java.lang.ClassNotFoundException: com.google.auth.oauth2.ServiceAccountJwtAccessCredentials
	at com.example.UptimeIT.test2_ListUptimeIps(UptimeIT.java:87)

[ERROR] com.example.UptimeIT.test2_UpdateUptimeCheck  Time elapsed: 0.027 s  <<< ERROR!
java.lang.NoClassDefFoundError: com/google/auth/oauth2/ServiceAccountJwtAccessCredentials
	at com.example.UptimeIT.test2_UpdateUptimeCheck(UptimeIT.java:68)
Caused by: java.lang.ClassNotFoundException: com.google.auth.oauth2.ServiceAccountJwtAccessCredentials
	at com.example.UptimeIT.test2_UpdateUptimeCheck(UptimeIT.java:68)

[ERROR] com.example.UptimeIT.test3_DeleteUptimeCheck  Time elapsed: 0.002 s  <<< ERROR!
java.lang.NoClassDefFoundError: com/google/auth/oauth2/ServiceAccountJwtAccessCredentials
	at com.example.UptimeIT.test3_DeleteUptimeCheck(UptimeIT.java:97)
Caused by: java.lang.ClassNotFoundException: com.google.auth.oauth2.ServiceAccountJwtAccessCredentials
	at com.example.UptimeIT.test3_DeleteUptimeCheck(UptimeIT.java:97)

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.003 s <<< FAILURE! - in com.example.DeleteNotificationChannelIT
[ERROR] com.example.DeleteNotificationChannelIT  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: com/google/auth/oauth2/ServiceAccountJwtAccessCredentials
	at com.example.DeleteNotificationChannelIT.setupClass(DeleteNotificationChannelIT.java:56)
Caused by: java.lang.ClassNotFoundException: com.google.auth.oauth2.ServiceAccountJwtAccessCredentials
	at com.example.DeleteNotificationChannelIT.setupClass(DeleteNotificationChannelIT.java:56)

[ERROR] Tests run: 5, Failures: 0, Errors: 4, Skipped: 1, Time elapsed: 0.115 s <<< FAILURE! - in com.example.AlertIT
[ERROR] com.example.AlertIT.testListPolicies  Time elapsed: 0.104 s  <<< ERROR!
java.lang.NoClassDefFoundError: com/google/auth/oauth2/ServiceAccountJwtAccessCredentials
	at com.example.AlertIT.testListPolicies(AlertIT.java:64)
Caused by: java.lang.ClassNotFoundException: com.google.auth.oauth2.ServiceAccountJwtAccessCredentials
	at com.example.AlertIT.testListPolicies(AlertIT.java:64)

[ERROR] com.example.AlertIT.testDisableEnablePolicies  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: com/google/auth/oauth2/ServiceAccountJwtAccessCredentials
	at com.example.AlertIT.testDisableEnablePolicies(AlertIT.java:98)
Caused by: java.lang.ClassNotFoundException: com.google.auth.oauth2.ServiceAccountJwtAccessCredentials
	at com.example.AlertIT.testDisableEnablePolicies(AlertIT.java:98)

[ERROR] com.example.AlertIT.testBackupPolicies  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: com/google/auth/oauth2/ServiceAccountJwtAccessCredentials
	at com.example.AlertIT.testBackupPolicies(AlertIT.java:70)
Caused by: java.lang.ClassNotFoundException: com.google.auth.oauth2.ServiceAccountJwtAccessCredentials
	at com.example.AlertIT.testBackupPolicies(AlertIT.java:70)

[ERROR] com.example.AlertIT.testReplaceChannels  Time elapsed: 0.002 s  <<< ERROR!
java.lang.NoClassDefFoundError: com/google/auth/oauth2/ServiceAccountJwtAccessCredentials
	at com.example.AlertIT.testReplaceChannels(AlertIT.java:85)
Caused by: java.lang.ClassNotFoundException: com.google.auth.oauth2.ServiceAccountJwtAccessCredentials
	at com.example.AlertIT.testReplaceChannels(AlertIT.java:85)

[ERROR] Errors:
[ERROR]   AlertIT.testBackupPolicies:70 » NoClassDefFound com/google/auth/oauth2/Service...
[ERROR]   AlertIT.testDisableEnablePolicies:98 » NoClassDefFound com/google/auth/oauth2/...
[ERROR]   AlertIT.testListPolicies:64 » NoClassDefFound com/google/auth/oauth2/ServiceAc...
[ERROR]   AlertIT.testReplaceChannels:85 » NoClassDefFound com/google/auth/oauth2/Servic...
[ERROR]   DeleteNotificationChannelIT.setupClass:56 » NoClassDefFound com/google/auth/oa...
[ERROR]   UptimeIT.test1_CreateUptimeCheck:62 » NoClassDefFound com/google/auth/oauth2/S...
[ERROR]   UptimeIT.test2_GetUptimeCheck:74 » NoClassDefFound com/google/auth/oauth2/Serv...
[ERROR]   UptimeIT.test2_ListUptimeChecks:80 » NoClassDefFound com/google/auth/oauth2/Se...
[ERROR]   UptimeIT.test2_ListUptimeIps:87 » NoClassDefFound com/google/auth/oauth2/Servi...
[ERROR]   UptimeIT.test2_UpdateUptimeCheck:68 » NoClassDefFound com/google/auth/oauth2/S...
[ERROR]   UptimeIT.test3_DeleteUptimeCheck:97 » NoClassDefFound com/google/auth/oauth2/S...
[ERROR] Tests run: 12, Failures: 0, Errors: 11, Skipped: 1
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.0.0-M4:verify (default) on project monitoring-google-cloud-v3-samples: There are test failures.
```

### PR DESCRIPTION
**Pull request by munkhuushmgl**
Fixes #3540 

I am not sure it is really good solution for this issue. I was able to make it pass adding the removed deps from previous PR.

- [X] Please **merge** this PR for me once it is approved.

### CODE REVIEW

**Comment by lesv** [comment]
Seems to have an issue.

**Comment by munkhuushmgl** [comment]
looks like it is flaky

**Comment by chingor13** [comment]
I don't understand how this is failing. If you run `mvn dependency:list` or `mvn dependency:tree` in the monitoring/cloud-client directory in #3534, it already shows it's resolving to 0.21.1 for google-auth-library-credentials and google-auth-library-oauth2-http

**Comment by munkhuushmgl** [comment]
> I don't understand how this is failing. If you run `mvn dependency:list` or `mvn dependency:tree` in the monitoring/cloud-client directory in #3534, it already shows it's resolving to 0.21.1 for google-auth-library-credentials and google-auth-library-oauth2-http

I do not have enough context on this, but when I upgrade to bom to 9.0.0 --> it fails with the following error:
```
java.lang.NoClassDefFoundError: com/google/auth/oauth2/ServiceAccountJwtAccessCredentials

	at com.google.cloud.monitoring.v3.stub.MetricServiceStubSettings.defaultCredentialsProviderBuilder(MetricServiceStubSettings.java:216)
	at com.google.cloud.monitoring.v3.stub.MetricServiceStubSettings$Builder.createDefault(MetricServiceStubSettings.java:587)
	at com.google.cloud.monitoring.v3.stub.MetricServiceStubSettings$Builder.access$000(MetricServiceStubSettings.java:471)
	at com.google.cloud.monitoring.v3.stub.MetricServiceStubSettings.newBuilder(MetricServiceStubSettings.java:240)
	at com.google.cloud.monitoring.v3.MetricServiceSettings$Builder.createDefault(MetricServiceSettings.java:208)
	at com.google.cloud.monitoring.v3.MetricServiceSettings$Builder.access$000(MetricServiceSettings.java:198)
	at com.google.cloud.monitoring.v3.MetricServiceSettings.newBuilder(MetricServiceSettings.java:180)
	at com.google.cloud.monitoring.v3.MetricServiceClient.create(MetricServiceClient.java:130)
	at com.example.monitoring.QuickstartSample.main(QuickstartSample.java:51)
	at com.example.monitoring.QuickstartSampleIT.testQuickstart(QuickstartSampleIT.java:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.lang.ClassNotFoundException: com.google.auth.oauth2.ServiceAccountJwtAccessCredentials
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 37 more
```

**Comment by chingor13** [comment]
Yeah, I see the error, but I'm not seeing why specifying the version here would fix it. Does it work without the version numbers?

**Comment by munkhuushmgl** [comment]
> Yeah, I see the error, but I'm not seeing why specifying the version here would fix it. Does it work without the version numbers?

It does work without the version number also:
```
    <!-- FIXME: remove after client fixes depenency issue => BOM 9.0.0   -->
    <dependency>
      <groupId>com.google.auth</groupId>
      <artifactId>google-auth-library-credentials</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.auth</groupId>
      <artifactId>google-auth-library-oauth2-http</artifactId>
    </dependency>
```

**Comment by chingor13** [comment]
Ok I figured it out - it's the interaction with the maven-flatten-plugin: google-cloud-monitoring declares google-auth-library-oauth2-http as a test dependency (which it is as far as the code in the client library). It normally gets the google-auth-library-oauth2-http library via gax, but maven-flatten-plugin is excluding it because the client library pom declares that artifact. It's stripped out of the flattened pom because it's a test dependency.
